name: Build on MacOS

on:
  push:
    branches: [ master ]
    tags:     [ REL_* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        shell: sh

    steps:
    - uses: actions/checkout@v3

    - name: start pg
      run: |
        brew services start postgresql

    - name: install lua
      run: |
        brew install lua@5.4.4

    - name: lua environment
      run: |
        (echo LUA="/usr/local/bin/lua"
         echo LUAC="/usr/local/bin/luac"
         echo LUA_INCDIR="/usr/local/include/lua"
         echo LUALIB="-L/usr/local/lib -llua"
        ) >>$GITHUB_ENV

    - name: build
      run:
        make && sudo -E make install

    - name: wait for pg
      run: |
        n=0
        while ! pg_isready; do [ $(( n += 1 )) -gt 10 ] && exit 1; sleep $n; done

    - name: test
      run: |
        time make installcheck

    - name: build and test hstore
      run: |
        make -C hstore && sudo -E make -C hstore install && time make -C hstore installcheck

    - name: show output
      if: always()
      run: |
        cat regression.diffs || true
        cat hstore/regression.diffs || true
